services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassu
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpressuser
      MARIADB_PASSWORD: wordpresspassu
    ports:
      - 3306:3306
    volumes:
      - ./tmp/db:/var/lib/mysql
    networks:
      - njetwork

  php-fpm:
    build:
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./wordpress:/var/www/html/public
    networks:
      - njetwork

  web:
    image: nginx
    volumes:
      - ./wordpress:/var/www/html/public
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - njetwork

networks:
  njetwork:
    driver: bridge
