services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassu
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpressuser
      MARIADB_PASSWORD: wordpresspassu
    ports:
      - 3306:3306
    volumes:
      - ./tmp/db:/var/lib/mysql
    networks:
      - njetwork

  php-fpm:
    build:
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./wordpress:/var/www/html/public
    networks:
      - njetwork
    extra_hosts:
      - "kide.tunk.io:host-gateway"

  web:
    image: nginx
    volumes:
      - ./wordpress:/var/www/html/public
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - njetwork
    extra_hosts:
      - "kide.tunk.io:host-gateway"

networks:
  njetwork:
    driver: bridge
